# Form implementation generated from reading ui file './src/ui//book_list.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.edit_book_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.edit_book_button.setObjectName("edit_book_button")
        self.horizontalLayout.addWidget(self.edit_book_button)
        self.delete_book = QtWidgets.QPushButton(parent=self.centralwidget)
        self.delete_book.setObjectName("delete_book")
        self.horizontalLayout.addWidget(self.delete_book)
        self.borrow_book = QtWidgets.QPushButton(parent=self.centralwidget)
        self.borrow_book.setObjectName("borrow_book")
        self.horizontalLayout.addWidget(self.borrow_book)
        self.return_book_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.return_book_button.setObjectName("return_book_button")
        self.horizontalLayout.addWidget(self.return_book_button)
        self.new_book_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.new_book_button.setObjectName("new_book_button")
        self.horizontalLayout.addWidget(self.new_book_button)
        self.print_cards_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.print_cards_button.setObjectName("print_cards_button")
        self.horizontalLayout.addWidget(self.print_cards_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 29))
        self.menubar.setObjectName("menubar")
        self.menuUsers = QtWidgets.QMenu(parent=self.menubar)
        self.menuUsers.setObjectName("menuUsers")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionManage = QtGui.QAction(parent=MainWindow)
        self.actionManage.setObjectName("actionManage")
        self.menuUsers.addAction(self.actionManage)
        self.menubar.addAction(self.menuUsers.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.search_button, self.borrow_book)
        MainWindow.setTabOrder(self.borrow_book, self.new_book_button)
        MainWindow.setTabOrder(self.new_book_button, self.edit_book_button)
        MainWindow.setTabOrder(self.edit_book_button, self.delete_book)
        MainWindow.setTabOrder(self.delete_book, self.print_cards_button)
        MainWindow.setTabOrder(self.print_cards_button, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.tableWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LibreLib"))
        self.edit_book_button.setText(_translate("MainWindow", "Edit Selected"))
        self.delete_book.setText(_translate("MainWindow", "Delete Selected"))
        self.borrow_book.setText(_translate("MainWindow", "Borrow Selected"))
        self.borrow_book.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.return_book_button.setText(_translate("MainWindow", "Return Selected"))
        self.new_book_button.setText(_translate("MainWindow", "New Book"))
        self.new_book_button.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.print_cards_button.setText(_translate("MainWindow", "Print cards"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.search_button.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.menuUsers.setTitle(_translate("MainWindow", "Users"))
        self.actionManage.setText(_translate("MainWindow", "Manage"))
        self.actionManage.setShortcut(_translate("MainWindow", "Ctrl+U"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
