# Form implementation generated from reading ui file './ui//users_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Users_editor(object):
    def setupUi(self, Users_editor):
        Users_editor.setObjectName("Users_editor")
        Users_editor.resize(705, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Users_editor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_usr_button = QtWidgets.QPushButton(parent=Users_editor)
        self.new_usr_button.setObjectName("new_usr_button")
        self.horizontalLayout.addWidget(self.new_usr_button)
        self.delete_usr_button = QtWidgets.QPushButton(parent=Users_editor)
        self.delete_usr_button.setObjectName("delete_usr_button")
        self.horizontalLayout.addWidget(self.delete_usr_button)
        self.edit_usr_button = QtWidgets.QPushButton(parent=Users_editor)
        self.edit_usr_button.setObjectName("edit_usr_button")
        self.horizontalLayout.addWidget(self.edit_usr_button)
        self.print_usr_button = QtWidgets.QPushButton(parent=Users_editor)
        self.print_usr_button.setObjectName("print_usr_button")
        self.horizontalLayout.addWidget(self.print_usr_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_Button = QtWidgets.QPushButton(parent=Users_editor)
        self.search_Button.setObjectName("search_Button")
        self.horizontalLayout_2.addWidget(self.search_Button)
        self.search_edit = QtWidgets.QLineEdit(parent=Users_editor)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout_2.addWidget(self.search_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table_users = QtWidgets.QTableWidget(parent=Users_editor)
        self.table_users.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.table_users.setObjectName("table_users")
        self.table_users.setColumnCount(0)
        self.table_users.setRowCount(0)
        self.verticalLayout.addWidget(self.table_users)

        self.retranslateUi(Users_editor)
        self.search_edit.editingFinished.connect(self.search_Button.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Users_editor)
        Users_editor.setTabOrder(self.new_usr_button, self.delete_usr_button)
        Users_editor.setTabOrder(self.delete_usr_button, self.edit_usr_button)
        Users_editor.setTabOrder(self.edit_usr_button, self.print_usr_button)
        Users_editor.setTabOrder(self.print_usr_button, self.table_users)

    def retranslateUi(self, Users_editor):
        _translate = QtCore.QCoreApplication.translate
        Users_editor.setWindowTitle(_translate("Users_editor", "Users"))
        self.new_usr_button.setText(_translate("Users_editor", "New"))
        self.delete_usr_button.setText(_translate("Users_editor", "Delete"))
        self.edit_usr_button.setText(_translate("Users_editor", "Edit"))
        self.print_usr_button.setText(_translate("Users_editor", "Print Card"))
        self.search_Button.setText(_translate("Users_editor", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Users_editor = QtWidgets.QDialog()
    ui = Ui_Users_editor()
    ui.setupUi(Users_editor)
    Users_editor.show()
    sys.exit(app.exec())
