# Form implementation generated from reading ui file './ui/user_edit_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_user_edit_dialog(object):
    def setupUi(self, user_edit_dialog):
        user_edit_dialog.setObjectName("user_edit_dialog")
        user_edit_dialog.resize(400, 270)
        self.verticalLayout = QtWidgets.QVBoxLayout(user_edit_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(parent=user_edit_dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.id_edit = QtWidgets.QLineEdit(parent=user_edit_dialog)
        self.id_edit.setReadOnly(True)
        self.id_edit.setObjectName("id_edit")
        self.horizontalLayout_4.addWidget(self.id_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=user_edit_dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.name_edit = QtWidgets.QLineEdit(parent=user_edit_dialog)
        self.name_edit.setObjectName("name_edit")
        self.horizontalLayout_3.addWidget(self.name_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(parent=user_edit_dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.surename_edit = QtWidgets.QLineEdit(parent=user_edit_dialog)
        self.surename_edit.setObjectName("surename_edit")
        self.horizontalLayout.addWidget(self.surename_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(parent=user_edit_dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.p_number_edit = QtWidgets.QLineEdit(parent=user_edit_dialog)
        self.p_number_edit.setObjectName("p_number_edit")
        self.horizontalLayout_2.addWidget(self.p_number_edit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=user_edit_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(user_edit_dialog)
        self.buttonBox.accepted.connect(user_edit_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(user_edit_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(user_edit_dialog)
        user_edit_dialog.setTabOrder(self.name_edit, self.surename_edit)
        user_edit_dialog.setTabOrder(self.surename_edit, self.p_number_edit)
        user_edit_dialog.setTabOrder(self.p_number_edit, self.id_edit)

    def retranslateUi(self, user_edit_dialog):
        _translate = QtCore.QCoreApplication.translate
        user_edit_dialog.setWindowTitle(_translate("user_edit_dialog", "Dialog"))
        self.label.setText(_translate("user_edit_dialog", "ID: "))
        self.label_2.setText(_translate("user_edit_dialog", "Name: "))
        self.label_3.setText(_translate("user_edit_dialog", "Surename: "))
        self.label_4.setText(_translate("user_edit_dialog", "Phone number: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    user_edit_dialog = QtWidgets.QDialog()
    ui = Ui_user_edit_dialog()
    ui.setupUi(user_edit_dialog)
    user_edit_dialog.show()
    sys.exit(app.exec())
